harness/harness-core-ui

src/modules/10-common/hooks/useTelemetry.ts
src/modules/75-ce/TrackingEventsConstants.ts
src/modules/75-ce/components/CESideNav/CESideNav.tsx
src/modules/75-ce/components/PerspectiveBuilder/PerspectiveBuilder.tsx
src/modules/75-ce/components/PerspectiveFilters/PerspectiveFilters.tsx
src/modules/75-ce/components/PerspectiveReportsAndBudget/PerspectiveReportsAndBudgets.tsx
src/modules/75-ce/components/PerspectiveViews/PerspectiveGridView.tsx
src/modules/75-ce/components/PerspectiveViews/PerspectiveListView.tsx
src/modules/75-ce/components/RecommendationDetails/RecommendationTabs.tsx
src/modules/75-ce/pages/perspective-details/PerspectiveDetailsPage.tsx
src/modules/75-ce/pages/perspective-list/PerspectiveListPage.tsx
src/modules/75-ce/pages/recommendationDetails/RecommendationDetailsPage.tsx
src/modules/75-ce/pages/recommendationList/RecommendationList.tsx

feat: [CCM-5317]: Added Tracking events in perspectives

---

src/framework/strings/languageLoader.ts
src/modules/10-common/.eslintrc.yml
src/modules/15-notifications/.eslintrc.yml
src/modules/18-audit-trail/.eslintrc.yml
src/modules/22-resource-center/.eslintrc.yml
src/modules/25-governance/.eslintrc.yml
src/modules/27-sto/.eslintrc.yml
tsconfig.json

feat: [COMP-3475]: Add STO module into Core UI

---

src/modules/70-pipeline/pages/pipelines/__tests__/__snapshots__/PipelinesPage.test.tsx.snap
src/modules/70-pipeline/pages/pipelines/views/PipelineCard/PipelineCard.module.scss
src/modules/70-pipeline/pages/pipelines/views/PipelineCard/PipelineCard.module.scss.d.ts
src/modules/70-pipeline/pages/pipelines/views/PipelineCard/PipelineCard.tsx

1. Implements UX feedback changes suggested by design team.
2. Fixes tooltip on non truncated word and other refactoring
Mocks link -> https://www.figma.com/file/HZSCsX1igZswK2J78oaZZc/L9?node-id=2787%3A165754
https://harness.atlassian.net/browse/PIE-2327
https://user-images.githubusercontent.com/96409598/150212448-c21e5c22-9ed9-42a6-8416-a69efbe9a962.mov

fix: [PIE-2327]: fixing non truncated word popover and other refactoring

---

src/modules/75-ce/components/COEcsSelector/COEcsSelector.module.scss
src/modules/75-ce/components/COEcsSelector/COEcsSelector.module.scss.d.ts
src/modules/75-ce/components/COEcsSelector/COEcsSelector.tsx
src/modules/75-ce/components/COEcsSelector/__tests__/COEcsSelector.test.tsx
src/modules/75-ce/components/COEcsSelector/__tests__/__snapshots__/COEcsSelector.test.tsx.snap
src/modules/75-ce/components/CORdsSelector/CORdsSelector.module.scss
src/modules/75-ce/components/CORdsSelector/CORdsSelector.module.scss.d.ts
src/modules/75-ce/components/CORdsSelector/CORdsSelector.tsx

fix: [LWG-1115]: radio button alignment for ECS and RDS selector table

---

cypress/fixtures/ng/api/connectors.json
cypress/integration/85-cv/HealthSource/AppDHealthSource.spec.ts
cypress/support/85-cv/monitoredService/constants.ts
cypress/support/85-cv/monitoredService/health-sources/AppDynamics/constants.ts
cypress/support/commands.ts
src/modules/85-cv/pages/health-source/connectors/AppDynamics/AppDHealthSource.utils.ts

feat: [CVS-9002]: automation for AppDynamics

---

src/modules/85-cv/components/MetricsDashboardList/MetricsDashboardList.tsx
src/modules/85-cv/components/MetricsDashboardList/MetricsDashboardList.utils.ts
src/modules/85-cv/components/MetricsDashboardList/tests/MetricDashboardList.test.tsx

Fixing the issue of error scenario coming below pagination for Datadog.
https://harness.atlassian.net/jira/software/c/projects/CVS/boards/102

feat: [CVS-8853]: fixing the issue of error scenario coming below pagination

---

src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.module.scss
src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.module.scss.d.ts
src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx

feat: [PL-20872]: Few Connector Reference fixes

---

src/modules/10-common/components/DelegateSelectionLogs/DelegateSelectionLogsTable.tsx
src/modules/10-common/components/DelegateSelectionLogs/DelegateSelectionLogsTask.tsx
src/modules/10-common/components/DelegateSelectionLogs/__tests__/__snapshots__/DelegateSelectionLogs.test.tsx.snap

fix: [DEL-3191]: del selection logs improvement

---

src/modules/85-cv/components/MultiItemsSideNav/MultiItemsSideNav.tsx
src/modules/85-cv/components/MultiItemsSideNav/components/SelectedAppsSideNav/components/GroupedSideNav/GroupedSideNav.tsx
src/modules/85-cv/components/MultiItemsSideNav/components/SelectedAppsSideNav/components/GroupedSideNav/GroupedSideNav.types.ts
src/modules/85-cv/pages/health-source/connectors/CustomHealthSource/CustomHealthSource.constants.ts
src/modules/85-cv/pages/health-source/connectors/CustomHealthSource/CustomHealthSource.tsx
src/modules/85-cv/pages/health-source/connectors/CustomHealthSource/CustomHealthSource.types.ts
src/modules/85-cv/pages/health-source/connectors/CustomHealthSource/CustomHealthSource.utils.ts
src/modules/85-cv/pages/health-source/connectors/CustomHealthSource/__tests__/CustomHealthSource.mock.ts
src/modules/85-cv/pages/health-source/connectors/NewRelic/NewRelicHealthSource.utils.tsx
src/modules/85-cv/pages/health-source/connectors/NewRelic/__tests__/NewRelic.mock.ts
src/modules/85-cv/pages/health-source/connectors/NewRelic/components/NewRelicCustomMetricForm/NewRelicCustomMetricForm.tsx
src/modules/85-cv/pages/health-source/connectors/PrometheusHealthSource/PrometheusHealthSource.tsx

1. For new relic default identifier is not coming up.
2. For custom metrics, default identifier is not coming up.
3. No data is passed in the parse sample data api 

fix: [CVS-9191]: Fix identifier issue for NewRelic and Custom HS

---

src/modules/70-pipeline/components/PipelineInputSetForm/PipelineInputSetForm.tsx
src/modules/70-pipeline/components/PipelineStudio/RightDrawer/__tests__/RightDrawer.test.tsx
src/modules/70-pipeline/components/PipelineVariablesContext/PipelineVariablesContext.tsx
src/modules/70-pipeline/components/RunPipelineModal/RunPipelineForm.tsx
src/modules/75-cd/pages/pipeline-deployment-list/__tests__/CDPipelineDeploymentList.test.tsx

fix: [PIE-2846]: multiple variables API call in run form

---

src/modules/30-delegates/components/DelegateTokens/modals/useCreateTokenModal.tsx

fix: [DEL-3162]: del uniqueness message from BE

---

src/modules/30-delegates/pages/delegates/DelegateListingItem.tsx
src/modules/35-connectors/components/CreateConnector/commonSteps/DelegateSelectorStep/DelegateSelector/DelegateSelector.tsx
src/modules/35-connectors/components/CreateConnector/commonSteps/DelegateSelectorStep/DelegateSelector/DelegateSelectorTable.tsx
src/services/portal/index.tsx
src/services/portal/swagger.json

fix: [DEL-3030]: del heartbeat now shown properly

---

src/modules/70-pipeline/components/PipelineStudio/PipelineCanvas/PipelineCanvas.tsx
src/modules/70-pipeline/strings/strings.en.yaml
src/stringTypes.ts

https://harness.atlassian.net/browse/CDS-34080
https://user-images.githubusercontent.com/96409598/155712504-3dbee03a-f2cd-4b0a-8371-3c03c5383998.mov

fix: [CDS-34080]: template saved label changed

---

src/modules/25-governance/GovernanceApp.jsx

Pass useFeatureFlags hook down to the governance MFE

feat: [FFM-2379]: Pass useFeatureFlags to opa MFE

---

src/modules/70-pipeline/components/RunPipelineModal/RunPipelineForm.tsx

On selectively selecting a stage, the form does not submit if the stage has lesser variables compared to the variables in all stages
https://harness.atlassian.net/browse/PIE-3077
Before:
https://user-images.githubusercontent.com/96711906/158518964-438ec130-d3e3-4552-b2a9-45ba290fd570.mov
After:
https://user-images.githubusercontent.com/96711906/158518925-ad89fea3-6a9d-461e-b0a4-02619e7ceafa.mov
- Fix Prettier - `fix …

fix: [PIE-3077]: run pipeline form selective stage submit error

---

configs/devServerProxy.config.js
cypress/integration/85-cv/HealthSource/DatadogHealthSource.spec.ts
cypress/integration/85-cv/HealthSource/Dynatrace.spec.ts
cypress/integration/85-cv/HealthSource/NewRelic.spec.ts
cypress/support/85-cv/monitoredService/health-sources/Datadog/constants.ts
src/modules/35-connectors/pages/connectors/utils/ConnectorListViewUtils.tsx
src/modules/85-cv/pages/health-source/connectors/CustomHealthSource/CustomHealthSource.tsx
src/modules/85-cv/pages/health-source/connectors/CustomHealthSource/components/MapMetricsToServices/MapMetricsToServices.tsx
src/modules/85-cv/pages/health-source/connectors/DatadogMetricsHealthSource/DatadogMetricsHealthSource.utils.ts
src/modules/85-cv/pages/health-source/connectors/DatadogMetricsHealthSource/tests/DatadogMetricsHealthSource.test.tsx
src/modules/85-cv/pages/health-source/connectors/NewRelic/NewRelicHealthSource.tsx
src/modules/85-cv/pages/health-source/connectors/NewRelic/NewRelicHealthSource.utils.tsx

feat: [SRM-9356]: Added missing test cases for newrelic and datadog

---

package.json
src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/HealthScoreChart/HealthScoreChart.tsx
src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/HealthScoreChart/__tests__/HealthScoreChart.test.tsx

feat: [SRM-9813]: hotfix for avoiding infinite calls in service health page

---

src/modules/85-cv/pages/health-source/HealthSourceTable/HealthSourceTable.utils.ts

Icon for Error Tracking Health Source
https://harness.atlassian.net/browse/SRM-9546

feat: [SRM-9546]: error tracking icon

---

cypress.json
cypress/integration/70-pipeline/PipelineCanvas.spec.ts
cypress/support/70-pipeline/constants.ts

Added explicit wait on API calls and element assertion
[https://harness.atlassian.net/browse/PIE-3078](https://harness.atlassian.net/browse/PIE-3078)

fix: [PIE-3078]: pageLoadTimeout updated and page load wait increased

---

Dockerfile

fixes security issue in libxml2

fix: [PL-23831]: upgrade libxml2

---

scripts/ci/auto-merge.sh

feat: [BT-1067]: Add auto-merge script

---

src/modules/70-pipeline/components/PipelineSteps/Steps/StepsValidateUtils.ts
src/modules/72-templates-library/components/PipelineSteps/TemplateStep/TemplateStepWidget/TemplateStepWidget.tsx

Added missing Identifier schema to show validation error message.
Step:
Step with Template:
https://harness.atlassian.net/browse/CI-3722

fix: [CI-3722]: Fixing identifier validation in Pipeline Steps

---

package.json
src/modules/35-connectors/components/CreateConnector/ErrorTrackingConnector/CreateErrorTrackingConnector.tsx
src/modules/35-connectors/components/CreateConnector/ErrorTrackingConnector/utils.ts
src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts

This reverts commit 609312a7b1d6a3ba9f94d64cd9297ceb96967fcf.
reverted change to remove the url from error tracking connector
https://harness.atlassian.net/browse/SRM-9821
https://user-images.githubusercontent.com/2991478/163236640-e393ebe7-6b9a-452a-933c-92a78d61a706.png

Revert "feat: [SRM-9821]: error tracking remove url input (#8344)"

---

src/modules/70-pipeline/components/PipelineStudio/RightBar/RightBar.tsx

Changed button label to "Apply Changes" from "Save".

feat: [PIE-3510]: Updated button label on Codebase configuration modal

---

cypress/fixtures/ng/api/projects/project1.json
cypress/fixtures/ng/api/projects/project2.json
src/framework/AppStore/AppStoreContext.tsx
src/framework/PreferenceStore/PreferenceStoreContext.tsx
src/framework/PreferenceStore/__tests__/PreferenceStoreContext.test.tsx
src/framework/app/App.tsx
src/framework/utils/AppStorage.ts
src/modules/10-common/utils/testUtils.tsx
src/modules/35-connectors/components/ConnectorResourceModalBody/__tests__/ConnectorResourceModalBody.test.tsx
src/modules/45-projects-orgs/modals/ProjectModal/views/EditProject.tsx
src/modules/45-projects-orgs/pages/projects/DeleteProject.tsx
src/modules/45-projects-orgs/pages/projects/ProjectsPage.tsx
src/modules/75-cf/components/CreateFlagDialog/__tests__/FlagDialog.test.tsx
src/modules/75-cf/components/CreateFlagWizard/__tests__/FlagWizard.test.tsx

https://harness.atlassian.net/browse/PL-23322

feat: [PL-23322]: PreferenceFramework to retain scoped preferences in localStorage

---

src/modules/75-cf/components/EditVariationsModal/__tests__/EditVariationsModal.test.tsx

feat: [PIE-2618]: unskip test

---

src/modules/70-pipeline/components/RunPipelineModal/__tests__/useInputSets.test.tsx
src/modules/70-pipeline/utils/__tests__/runPipelineUtils.test.tsx

chore: [PIE-3577]: add test cases for regressions

---

src/modules/70-pipeline/components/GitPopover/GitPopover.tsx

**Before:**
https://user-images.githubusercontent.com/73115842/164214826-7a6a6464-ebee-4683-89fd-c1e8d07e4d64.mov
**After**
https://user-images.githubusercontent.com/73115842/164214879-ceb507d5-e098-420a-a176-8b735df464b4.mov

fix: [PL-24226]: auto pop over fix

---

src/modules/75-ce/components/AnomaliesFilter/AnomaliesFilter.tsx
src/modules/75-ce/components/AnomaliesFilter/FilterDrawer/AnomaliesFilterForm.tsx
src/modules/75-ce/components/AnomaliesFilter/FilterDrawer/AnomalyFilterForm.module.scss
src/modules/75-ce/components/AnomaliesFilter/FilterDrawer/FilterDrawer.tsx
src/modules/75-ce/components/AnomaliesFilter/FilterDrawer/utils.ts
src/modules/75-ce/utils/anomaliesUtils.ts
src/services/ce/index.tsx
src/services/ce/swagger.json

https://harness.atlassian.net/browse/CCM-7889

feat: [CCM-7889]: Azure Filter Support in Anomalies Filter Panel

---

src/modules/10-common/navigation/ProjectSetupMenu/ProjectSetupMenu.tsx
src/modules/85-sto-steps/components/STOSideNav/STOSideNav.tsx
src/modules/85-sto-steps/components/STOSideNav/__test__/__snapshots__/STOSideNav.test.tsx.snap

feat: [STO-4486]: STO Project setup menu

---

src/modules/70-pipeline/components/ExpandErrorModal/useExpandErrorModal.tsx
src/modules/70-pipeline/pages/execution/ExecutionTestView/BuildTests.module.scss
src/modules/70-pipeline/pages/execution/ExecutionTestView/BuildTests.module.scss.d.ts
src/modules/70-pipeline/pages/execution/ExecutionTestView/TestsExecutionItem.tsx
src/modules/70-pipeline/pages/execution/ExecutionTestView/TestsFailedPopover.tsx
src/modules/70-pipeline/pages/execution/ExecutionTestView/__test__/__snapshots__/BuildTests.test.tsx.snap

Initial Issue here: https://harness.atlassian.net/browse/CI-4029
https://user-images.githubusercontent.com/43422351/173701029-041878bc-6224-4d08-a011-f49448380fa8.mov

fix: [CI-4029]: test details popup

---

configs/devServerProxy.config.js

fix: [PL-25920]: Chaos UI MFE proxy URL

---

src/microfrontends/package.json

Summary: bumped mfe library version
[cds](https://harness.atlassian.net/browse/CDS-39023)

fix: [CDS-39023]: bump mfe library

---

src/modules/28-et/ErrorTrackingApp.tsx
src/modules/70-pipeline/pages/execution/ExecutionErrorTrackingView/ExecutionErrorTrackingView.tsx

feat: [SRM-10885]: Add the ability to navigate back from the arc screen

---

src/modules/70-pipeline/components/ArtifactsSelection/ArtifactHelper.ts
src/modules/70-pipeline/components/ArtifactsSelection/__tests__/ArtifactSelection.test.tsx

https://harness.atlassian.net/browse/CDS-38857

feat: [CDS-38857]: allow adding ECR artifact to serverless stage

---

src/modules/85-cv/components/Notifications/components/useSRMNotificationModal/useSRMNotificationModal.mock.ts
src/modules/85-cv/components/Notifications/components/useSRMNotificationModal/useSRMNotificationModal.test.tsx
src/modules/85-cv/components/Notifications/components/useSRMNotificationModal/useSRMNotificationModal.utils.ts

1. Fixing a scenario where empty conditions are passed in notifications.
NA
<details>
</details>
<details>
</details>

feat: [SRM-10866]: fixing a scenario

---

src/framework/app/App.tsx

NA
<details>
</details>
<details>
</details>

feat: [PL-25761]: 429 generic handling

---

src/modules/85-cv/pages/components/UserHint/UserHint.constant.ts
src/modules/85-cv/pages/components/UserHint/UserHint.tsx
src/modules/85-cv/pages/components/UserHint/UserHint.types.ts
src/modules/85-cv/pages/components/UserHint/__tests__/UserHint.test.tsx
src/modules/85-cv/pages/slos/CVSLODetailsPage/DetailsPanel/DetailsPanel.tsx
src/modules/85-cv/pages/slos/CVSLOsListingPage.types.ts
src/modules/85-cv/pages/slos/SLOCard/SLOCardContent.tsx
src/modules/85-cv/pages/slos/__tests__/SLOCardContent.test.tsx

NA
<details>
</details>
<details>
</details>

fix: [SRM-11013]: Hide user hint in SLO listing page

---

src/modules/70-pipeline/components/PipelineInputSetForm/StageInputSetForm.tsx
src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/EnvironmentDetails.tsx
src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/InfrastructureDefinition/InfrastructureModal.tsx
src/modules/75-cd/components/PipelineSteps/DeployEnvStep/DeployEnvStep.tsx
src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployClusters/DeployClusters.module.scss
src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployClusters/DeployClusters.tsx
src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployEnvironment/DeployEnvironment.tsx
src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployEnvironmentOrEnvGroup/DeployEnvironmentOrEnvGroup.tsx
src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureInputStep.tsx
src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/DeployInfrastructureStep.tsx
src/modules/75-cd/components/PipelineSteps/DeployInfrastructureStep/utils.ts
src/modules/75-cd/components/PipelineStudio/DeployEnvSpecifications/DeployEnvSpecifications.tsx

Gitops clusters as runtime input and environment bug fixes
NA
<details>
</details>
<details>
</details>

feat: [CDS-39618]: gitops clusters as runtime input and environment bug fixes

---

src/modules/10-common/components/ResourceCenter/ResourceCenter.tsx

removes FF as requested in https://harness.atlassian.net/browse/PLG-1357
NA
<details>
</details>
<details>
</details>

fix: [PLG-1357]: Removed EARLY_ACCESS_ENABLED FF

---

src/modules/70-pipeline/components/PipelineStudio/PipelineTemplateBuilder/TemplatePipelineCanvas/__tests__/TemplatePipelineCanvas.test.tsx
src/modules/70-pipeline/utils/stageHelpers.ts
src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/DeployServiceSpecifications.tsx

NA
<details>
</details>
<details>
</details>

fix: [PIE-3977]: removed template serviceDefinition API call from DeployServiceSpecifications

---

cypress/integration/70-pipeline/ExecutionHistory.spec.ts
cypress/integration/70-pipeline/PipelineCanvas.spec.ts
cypress/integration/70-pipeline/PipelineExecution.spec.ts
src/index.html
src/modules/70-pipeline/components/PipelineStudio/PipelineQueryParamState/usePipelineQueryParam.ts
src/modules/70-pipeline/components/PipelineStudio/StageBuilder/StageBuilder.tsx
src/modules/70-pipeline/pages/inputSet-list/InputSetList.tsx
src/modules/70-pipeline/pages/inputSet-list/__tests__/__snapshots__/InputSetList.test.tsx.snap
src/modules/70-pipeline/pages/pipeline-deployment-list/PipelineDeploymentList.tsx
src/modules/70-pipeline/pages/pipeline-deployment-list/__tests__/__snapshots__/PipelineDeploymentList.test.tsx.snap
src/modules/70-pipeline/pages/pipelines/PipelinesPage.tsx
src/modules/70-pipeline/pages/pipelines/__tests__/__snapshots__/PipelinesPage.test.tsx.snap
src/modules/72-triggers/pages/triggers/__tests__/__snapshots__/TriggersPage.test.tsx.snap
src/modules/72-triggers/pages/triggers/views/TriggersList.tsx
src/modules/75-cd/pages/pipeline-deployment-list/__tests__/__snapshots__/CDPipelineDeploymentList.test.tsx.snap
src/modules/75-cf/pages/pipeline-deployment-list/__tests__/__snapshots__/CFPipelineDeploymentList.test.tsx.snap
src/modules/75-ci/pages/pipeline-deployment-list/__tests__/__snapshots__/CIPipelineDeploymentList.test.tsx.snap

integerated help panels for pipelien studio screens , input set , triggers and execution history page
https://user-images.githubusercontent.com/64455881/177117824-bc4110a3-4ae5-4cba-9c68-96a0ee2d4089.mov
<details>
</details>
<details>
</details>

feat: [CDS-39172]: help panel for pipeline studio

---

package.json

NA
<details>
</details>
<details>
</details>

fix: [BT-1550]:Ignore .sh and .md files in new file check

---

src/modules/10-common/strings/strings.en.yaml
src/modules/10-common/utils/Validation.tsx
src/modules/70-pipeline/components/PipelineSteps/Steps/__tests__/StepsValidateUtils.test.ts
src/stringTypes.ts

Before
After
NA
<details>
</details>
<details>
</details>

fix: [PL-21354]: Identifier 1st letter to uppercase

---

.husky/commit-msg
src/microfrontends/package.json

NA
<details>
</details>
<details>
</details>

chore: [CCM-8061]: Microfrontend types version update

---

src/modules/75-ce/RouteDestinations.tsx
src/modules/75-ce/components/COGatewayReview/COGatewayReview.module.scss.d.ts

NA
<details>
</details>
<details>
</details>

feat: [CCM-8098]: Moved Recommendations list page to CCM Microfrontend

---

src/modules/10-common/interfaces/RouteInterfaces.ts
src/modules/72-templates-library/pages/TemplatesPage/TemplatesPageUtils.tsx
src/modules/72-templates-library/utils/templatesUtils.ts
src/services/pipeline-ng/index.tsx
src/services/template-ng/index.tsx

NA
<details>
</details>
<details>
</details>

feat: [PL-26973]: Changed Script Template to Secret Manager Template

---

src/modules/75-cd/components/PipelineSteps/SshWinRmAzureInfrastructureSpec/SshWinRmAzureInfrastructureForm.tsx
src/modules/75-cd/components/PipelineSteps/SshWinRmAzureInfrastructureSpec/SshWinRmAzureInfrastructureSpec.tsx
src/modules/75-cd/components/PipelineSteps/SshWinRmAzureInfrastructureSpec/__tests__/SshWinRmAzureInfrastructureSpec.test.tsx

NA
<details>
</details>
<details>
</details>

fix: [cds-40597]: azure fixes

---

src/modules/85-sto-steps/components/STOExecutionCardSummary/STOExecutionCardSummary.tsx
src/modules/85-sto-steps/components/STOExecutionCardSummary/__tests__/STOExecutionCardSummary.test.tsx
src/modules/85-sto-steps/components/STOExecutionCardSummary/__tests__/__snapshots__/STOExecutionCardSummary.test.tsx.snap
src/modules/85-sto-steps/strings/strings.en.yaml
src/stringTypes.ts

Issue counts should be shown if they exist regardless of pipeline failure.
<details>
</details>

fix: [STO-4769]: Execution Card Issues

---

src/modules/70-pipeline/components/LogsContent/LogsState/createSections.ts

NA
<details>
</details>
<details>
</details>

fix: [PIE-3685]: handle manual intervention logs

---

src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx

https://user-images.githubusercontent.com/73115842/181025342-cf1d8dae-290d-46f3-91d7-6541e28769e5.mov
https://user-images.githubusercontent.com/73115842/181025453-1417ae6c-6b46-4d7a-8f9f-b79be8753822.mov
NA
<details>
</details>
<details>
</details>

fix: [PL-25666]: connector status red after new connector

---

src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
src/modules/70-pipeline/components/PipelineInputSetForm/__tests__/__snapshots__/CICodebaseInputSetForm.test.tsx.snap

…tting updated with status
NA
https://user-images.githubusercontent.com/73115842/181163134-b10c894f-4480-4942-9542-6268f066f18d.mov
<details>
</details>
<details>
</details>

fix: [PL-26951]: connector status in multi type connector field status update

---

src/modules/75-ce/components/CloudCostInsightChart/Chart.tsx
src/modules/75-ce/components/CloudCostInsightChart/ChartLegend.tsx
src/modules/75-ce/components/PerspectiveExplorerGroupBy/PersepectiveExplorerGroupBy.module.scss
src/modules/75-ce/components/PerspectivePreferences/PerspectivePreferences.tsx
src/modules/75-ce/pages/perspective-details/PerspectiveDetailsPage.module.scss
src/modules/75-ce/pages/perspective-details/PerspectiveDetailsPage.module.scss.d.ts
src/modules/75-ce/pages/perspective-details/PerspectiveDetailsPage.tsx
src/modules/75-ce/pages/perspective-details/__test__/__snapshots__/PerspectiveDetailsPage.test.tsx.snap
src/modules/75-ce/strings/strings.en.yaml

This PR addresses the review comments of #9315 and UX enhancements. 
| Before | After |
|:---:|:---:|
| <img width="431" alt="Screenshot 2022-07-23 at 8 10 06 PM" src="https://user-images.githubusercontent.com/97532027/180609904-1344a107-bf39-47f6-a986-6eede76fa1d3.png"> | <img width="431" alt="Screenshot 2022-07-23 at 8 09 46 PM" src="https://user-images.githubusercontent.com/97532027/180609905-468999aa-1937-4655-8117-0626c262c7b5.png"> |
<details>
</details>
<details>
- Build: …

fix: [CCM-8328]: Perspective Preferences Enhancements

---

src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureInterface.tsx
src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/AzureWebAppInfrastructureSpecEditable.tsx
src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/__tests__/AzureWebAppInfrastructureStep.test.tsx
src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/__tests__/__snapshots__/AzureWebAppInfrastructureStep.test.tsx.snap
src/modules/75-cd/components/PipelineSteps/AzureWebAppInfrastructureStep/__tests__/mocks.ts

added test cases for Azure web app infra
https://harness.atlassian.net/browse/PIE-4439
<details>
</details>
<details>
</details>

fix: [PIE-4439]: added test cases for Azure web app infra

---

src/modules/75-ce/components/AnomaliesAlert/NotificationMethod.tsx
src/modules/75-ce/components/AnomaliesAlert/__test__/NotificationMethod.test.tsx
src/modules/75-ce/components/AnomaliesAlert/__test__/__snapshots__/NotificationMethod.test.tsx.snap

Resolved flaky test cases
NA
<details>
</details>
<details>
</details>

feat: [CCM-8227]: Fixed flaky testcases

---

package.json
src/modules/35-connectors/common/VerifyOutOfClusterDelegate/VerifyOutOfClusterDelegate.tsx
src/modules/35-connectors/components/CreateConnector/GithubConnector/CreateGithubConnector.tsx
src/modules/35-connectors/components/CreateConnector/GithubConnector/StepAuth/StepGithubAuthentication.tsx
src/modules/35-connectors/components/CreateConnector/commonSteps/ConnectivityModeStep/ConnectivityModeStep.tsx
src/modules/35-connectors/components/CreateConnector/commonSteps/GitDetailsStep.tsx
src/modules/35-connectors/components/CreateConnectorWizard/__tests__/__snapshots__/CreateConnectorWizard.test.tsx.snap
src/modules/75-cd/components/Environments/Environments.tsx
src/modules/75-cd/components/Environments/__test__/__snapshots__/Environments.test.tsx.snap
src/modules/75-cd/components/Services/ServicesDashboardPage/ServicesDashboardPage.tsx
src/modules/75-cd/components/Services/ServicesGridView/ServicesGridView.tsx
src/modules/75-cd/components/Services/ServicesListView/ServicesListView.tsx
src/modules/75-cd/components/Services/__tests__/__snapshots__/Services.test.tsx.snap
src/modules/75-cd/components/Services/__tests__/__snapshots__/ServicesGridView.test.tsx.snap
src/modules/75-cd/components/Services/__tests__/__snapshots__/ServicesListPage.test.tsx.snap
src/modules/75-cd/components/Services/__tests__/__snapshots__/ServicesListView.test.tsx.snap

NA
<details>
</details>
<details>
</details>

feat: [CDS-41177]: hotfix for help panels for git hub , service listing pages and env pages

---

src/modules/85-cv/pages/slos/CVSLODetailsPage/CVSLODetailsPage.module.scss
src/modules/85-cv/pages/slos/CVSLODetailsPage/CVSLODetailsPage.module.scss.d.ts
src/modules/85-cv/pages/slos/CVSLODetailsPage/CVSLODetailsPage.tsx
src/modules/85-cv/pages/slos/CVSLODetailsPage/DetailsPanel/DetailsPanel.module.scss
src/modules/85-cv/pages/slos/CVSLODetailsPage/DetailsPanel/DetailsPanel.module.scss.d.ts
src/modules/85-cv/pages/slos/CVSLODetailsPage/DetailsPanel/DetailsPanel.tsx
src/modules/85-cv/pages/slos/CVSLODetailsPage/__test__/__snapshots__/CVSLODetailsPage.test.tsx.snap

NA
<details>
</details>
<details>
</details>

feat: [SRM-11319]: fixing the empty space on slo detailas page

---

src/modules/72-templates-library/components/TemplateStudio/TemplateStudioWrapper.tsx
src/modules/72-templates-library/components/TemplateStudio/__tests__/TemplateStudioWrapper.test.tsx

NA
<details>
</details>
<details>
</details>

fix: [CDS-41193]: stage selection for account/org template

---

package.json
src/modules/35-connectors/components/CreateConnector/GithubConnector/StepAuth/StepGithubAuthentication.tsx
src/modules/35-connectors/components/CreateConnector/GithubConnector/__test__/__snapshots__/CreateGithubConnector.test.tsx.snap
src/modules/35-connectors/components/CreateConnector/GitlabConnector/StepAuth/StepGitlabAuthentication.tsx
src/modules/35-connectors/components/CreateConnector/GitlabConnector/__test__/__snapshots__/CreateGitlabConnector.test.tsx.snap

NA
<details>
</details>
<details>
</details>

fix: [PIE-4757]: fixing width for git connectors

---

package.json
src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx

NA
<details>
</details>
<details>
</details>

fix: [CDS-42132]: loading when template save fails

---

src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentConfigCanvas.tsx
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateCanvasWrapper.tsx
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/DeploymentConfigForm.tsx
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/DeploymentInfraWrapper/__tests__/DeploymentInfraWrapper.test.tsx
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/DeploymentConfigStepDrawer/DeploymentConfigStepDrawer.module.scss
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/DeploymentConfigStepDrawer/DeploymentConfigStepDrawer.module.scss.d.ts
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/DeploymentConfigStepDrawer/DeploymentConfigStepDrawer.tsx
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/DeploymentConfigStepDrawer/DeploymentConfigStepDrawerTitle.tsx
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/ExecutionPanel/ExecutionPanel.module.scss
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/ExecutionPanel/ExecutionPanel.module.scss.d.ts
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/ExecutionPanel/ExecutionPanel.tsx
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/ExecutionPanel/ExecutionPanelUtils.tsx
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/StepTemplateCard/StepTemplateCard.module.scss
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/StepTemplateCard/StepTemplateCard.module.scss.d.ts
src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/StepTemplateCard/StepTemplateCard.tsx
src/modules/75-cd/context/DeploymentContext/DeploymentContextProvider.tsx
src/modules/75-cd/strings/strings.en.yaml
src/stringTypes.ts

NA
<details>
</details>
<details>
</details>

fix: [CDS-41588]: Execution tab support

---

src/modules/75-ce/components/CloudCostInsightChart/Chart.tsx

NA
<details>
</details>
<details>
</details>

fix: [CCM-8794]: Fix Perspective Chart Colors

---

cypress/integration/85-cv/HealthSource/CloudWatch.spec.ts
cypress/support/85-cv/monitoredService/constants.ts
cypress/support/85-cv/monitoredService/health-sources/CloudWatch/constants.ts
src/modules/85-cv/pages/health-source/common/CustomMetricV2/CustomMetric.types.ts
src/modules/85-cv/pages/health-source/common/CustomMetricV2/CustomMetric.utils.ts
src/modules/85-cv/pages/health-source/common/CustomMetricV2/components/HealthSourceServicesV2/__tests__/HealthSourceServicesV2.test.tsx
src/modules/85-cv/pages/health-source/common/CustomMetricV2/components/HealthSourceServicesV2/index.tsx
src/modules/85-cv/pages/health-source/common/SelectHealthSourceServices/SelectHealthSourceServices.tsx
src/modules/85-cv/pages/health-source/common/SelectHealthSourceServices/SelectHealthSourceServices.types.ts
src/modules/85-cv/pages/health-source/common/SelectHealthSourceServices/components/RiskProfile/RiskProfile.tsx
src/modules/85-cv/pages/health-source/common/SelectHealthSourceServices/components/RiskProfile/RiskProfile.utils.ts
src/modules/85-cv/pages/health-source/connectors/CloudWatch/CloudWatch.tsx
src/modules/85-cv/pages/health-source/connectors/CloudWatch/CloudWatch.types.ts
src/modules/85-cv/pages/health-source/connectors/CloudWatch/CloudWatch.utils.ts
src/modules/85-cv/pages/health-source/connectors/CloudWatch/__tests__/CloudWatch.mock.ts
src/modules/85-cv/pages/health-source/connectors/CloudWatch/__tests__/CloudWatch.test.tsx
src/modules/85-cv/pages/health-source/connectors/CloudWatch/__tests__/CloudWatch.utils.test.ts
src/modules/85-cv/pages/health-source/connectors/CloudWatch/components/components/components/CloudWatchForm.tsx
src/modules/85-cv/pages/monitored-service/__tests__/MonitoredServicePage.test.tsx
src/modules/85-cv/pages/slos/__tests__/CVSLOsListingPage.mock.ts
src/modules/85-cv/pages/slos/__tests__/__snapshots__/CVSLOsListingPage.test.tsx.snap
src/modules/85-cv/strings/strings.en.yaml
src/services/cv/index.tsx
src/services/cv/overrides.yaml
src/services/cv/swagger.json
src/stringTypes.ts

<details>
</details>
<details>
</details>

fix: [SRM-12431]: Update cloud watch risk profile

---

src/modules/85-cv/pages/slos/__tests__/__snapshots__/CVSLOsListingPage.test.tsx.snap
src/modules/85-cv/pages/slos/components/SLOActions/SLOActions.module.scss
src/modules/85-cv/pages/slos/components/SLOActions/SLOActions.module.scss.d.ts
src/modules/85-cv/pages/slos/components/SLOActions/SLOActions.tsx

NA
<details>
</details>
<details>
</details>

feat: [SRM-12535]: adding css for slo slo actions icons

---

src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionTabs/ExecutionTabs.tsx
src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/ErrorTracking.tsx

Updated microfronted routes for ET microfronted to accomodate for different use cases.
NA
<details>
</details>
<details> …

feat: [SRM-12541]: Changed microfrontend routes

---

cypress/integration/72-freeze-windows/OrgLevelFreeze.spec.ts
cypress/integration/72-freeze-windows/ProjectLevelFreeze.spec.ts
src/modules/45-projects-orgs/pages/organizations/OrganizationDetails/OrganizationDetailsPage.module.scss
src/modules/72-freeze-windows/components/FreezeWindowScheduleSection/FreezeWindowScheduleSection.tsx
src/modules/72-freeze-windows/components/FreezeWindowStudioBody/FreezeWindowStudioBody.module.scss
src/modules/72-freeze-windows/components/FreezeWindowStudioBody/FreezeWindowStudioBody.tsx
src/modules/72-freeze-windows/components/FreezeWindowStudioBody/FreezeWindowStudioYAMLView.tsx
src/modules/72-freeze-windows/components/FreezeWindowStudioConfigSection/ConfigViewModeRenderer.tsx
src/modules/72-freeze-windows/components/FreezeWindowStudioConfigSection/FreezeWindowStudioConfigSection.module.scss
src/modules/72-freeze-windows/components/__tests__/FreezeWindowStudioConfigSection.test.tsx
src/modules/72-freeze-windows/components/__tests__/FreezewindowStudioBody.test.tsx
src/modules/72-freeze-windows/components/__tests__/__snapshots__/FreezeWindowStudioConfigSection.test.tsx.snap
src/modules/72-freeze-windows/components/__tests__/__snapshots__/FreezewindowStudioBody.test.tsx.snap

NA
<details>
</details>
<details>
</details>

feat: [CDS-45052]: Freeze Config - UX Feedback

---

src/modules/70-pipeline/components/PipelineStudio/RightDrawer/RightDrawer.tsx

https://user-images.githubusercontent.com/98508399/200713366-ec0d54e4-de68-456e-8adf-01a50cf1a065.mov
<details>
</details>
<details>
- Fix Prettier: `fix …

feat: [PIE-5206]: Added deafult unique name and identifier for steps

---

src/modules/75-cd/components/GitOpsFetchLinkedApps/GitOpsFetchLinkedApps.tsx
src/modules/75-cd/components/GitOpsFetchLinkedApps/__tests__/GitOpsFetchLinkedApps.test.tsx
src/modules/75-cd/components/GitOpsFetchLinkedApps/__tests__/__snapshots__/GitOpsFetchLinkedApps.test.tsx.snap

NA
<details>
</details>
<details>
</details>

fix: [CDS-47642]: Enable Delegate Selector in GitopsFetchLinkedApps step

---

src/modules/85-cv/pages/slos/CVSLODetailsPage/CVSLODetailsPage.tsx
src/modules/85-cv/pages/slos/CVSLOsListingPage.tsx
src/modules/85-cv/pages/slos/__tests__/__snapshots__/CVSLOsListingPage.test.tsx.snap
src/modules/85-cv/pages/slos/components/CVCreateSLOV2/CVCreateSLOV2.tsx
src/modules/85-cv/pages/slos/components/CVCreateSLOV2/__tests__/__snapshots__/CVCreateSLOV2.test.tsx.snap
src/modules/85-cv/pages/slos/components/CVCreateSLOV2/components/CreateCompositeSloForm/components/AddSlos/components/SLOList.utils.tsx
src/modules/85-cv/pages/slos/components/SLODashbordFilters/SLODashbordFilters.tsx

followup pr for https://github.com/harness/harness-core-ui/pull/12917
NA
<details>
</details>
<details>
</details>

feat: [SRM-13213]: fixed PR comments on PR 12917

---

src/modules/10-common/RouteDefinitions.ts
src/modules/70-pipeline/pages/execution/ExecutionErrorTrackingView/ExecutionErrorTrackingView.tsx
src/modules/85-cv/RouteDestinations.tsx
src/modules/85-cv/components/LogsAnalysis/components/LogAnalysisRow/LogAnalysisRow.utils.ts
src/modules/85-cv/components/SideNav/__test__/__snapshots__/SideNav.test.tsx.snap
src/modules/85-cv/pages/code-errors/CVCodeErrors.tsx

and modify routes to match new format on ET MFE
Error Tracking MFE needed to move dependency of the header bar for our standalone experience from Harness Core UI to our own repository. In addition to those changes some small routing changes were necessary to accommodate routing changes in our MFE.
NA
<details>
</details>
<details>
- Rebase: …

feat: [SRM-12799]: Move Code Error headers to MFE

---

scripts/ci/release-branch-test-develop.sh

NA
<details>
</details>
<details>
</details>

Fix: [BT-2485]: hotfix notification for Ngui

---

package.json
src/modules/40-gitsync/components/DeprecatedCallout/DeprecatedCallout.module.scss
src/modules/40-gitsync/components/DeprecatedCallout/DeprecatedCallout.module.scss.d.ts
src/modules/40-gitsync/components/DeprecatedCallout/DeprecatedCallout.tsx
src/modules/40-gitsync/components/DeprecatedCallout/__tests__/DeprecatedCallout.test.tsx
src/modules/40-gitsync/components/DeprecatedCallout/__tests__/__snapshots__/DeprecatedCallout.test.tsx.snap
src/modules/40-gitsync/pages/GitSyncPage.tsx
src/modules/45-projects-orgs/pages/projects/views/ProjectDetails/ProjectDetails.tsx
src/modules/70-pipeline/pages/pipeline-list/PipelineListPage.tsx

Pushing changes of https://github.com/harness/harness-core-ui/pull/13461 to production
NA
<details>
</details>
<details>
- Fix …

feat: [PIE-7344]: Added support for oldGitSync DeprecatedCallout

---

src/modules/10-common/strings/strings.en.yaml
src/modules/75-cd/pages/get-started-with-cd/CDOnboardingActions.tsx
src/modules/75-cd/pages/get-started-with-cd/CDOnboardingStore.tsx
src/modules/75-cd/pages/get-started-with-cd/CDOnboardingUtils.tsx
src/modules/75-cd/pages/get-started-with-cd/ConfigureGitops/ConfigureGitops.tsx
src/modules/75-cd/pages/get-started-with-cd/ConfigureService/ConfigureService.tsx
src/modules/75-cd/pages/get-started-with-cd/DeployProvisioningWizard/Constants.ts
src/modules/75-cd/pages/get-started-with-cd/DeployProvisioningWizard/DeployProvisioningWizard.tsx
src/modules/75-cd/pages/get-started-with-cd/RunPipelineSummary/RunPipelineSummary.tsx
src/modules/75-cd/pages/get-started-with-cd/SelectWorkload/SelectDeploymentType.tsx
src/modules/75-cd/strings/strings.en.yaml
src/stringTypes.ts

NA
<details>
</details>
<details>
</details>

fix: [CDS-50935]: gitops onboarding configure step

---

src/modules/75-cd/pages/get-started-with-cd/DeployProvisioningWizard/Constants.ts
src/modules/75-cd/pages/get-started-with-cd/DeployProvisioningWizard/DeployProvisioningWizard.module.scss
src/modules/75-cd/pages/get-started-with-cd/DeployProvisioningWizard/DeployProvisioningWizard.tsx
src/modules/75-cd/pages/get-started-with-cd/GetStartedWithCD.module.scss
src/modules/75-cd/pages/get-started-with-cd/GetStartedWithCD.module.scss.d.ts
src/modules/75-cd/pages/get-started-with-cd/GitOpsAgent/GitOpsAgent.tsx
src/modules/75-cd/pages/get-started-with-cd/SelectWorkload/SelectDeploymentType.tsx

NA
<details>
</details>
<details>
</details>

feat: [CDS-50936]: PLG Gitops - Agent Screen

---

src/modules/33-auth-settings/components/Subscription/BillingInfo/BillingInfo.tsx
src/modules/33-auth-settings/components/Subscription/CostCalculator/__test__/CostCalculator.test.tsx
src/modules/33-auth-settings/modals/Subscription/__test__/useSubscriptionModal.test.tsx
src/services/cd-ng/index.tsx

NA
<details>
</details>
<details>
</details>

feat: [PLG-1705]: updating swagger

---

src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoInterface.ts
src/modules/70-pipeline/components/ManifestSelection/GitOps/ReleaseRepoWizard/__tests__/__snapshots__/RepoStore.test.tsx.snap
src/modules/70-pipeline/components/ManifestSelection/Manifesthelper.ts
src/modules/70-pipeline/components/ManifestSelection/__tests__/__snapshots__/ManifestSelection.test.tsx.snap
src/modules/70-pipeline/components/ManifestSelection/__tests__/__snapshots__/ManifestStore.test.tsx.snap

NA
<details>
</details>
<details>
</details>

feat: [CDS-52535]: Add BitBucket support in release repo

---

src/microfrontends/package.json
src/modules/75-idp/RouteDestinations.tsx
src/modules/75-idp/interfaces/IDPCustomMicroFrontendProps.types.ts

NA
<details>
</details>
<details>
</details>

[feat]:[IDP-104]: Updating the API exposed to IDP MFE

---

src/modules/10-common/RouteDefinitions.ts
src/modules/10-common/interfaces/RouteInterfaces.ts
src/modules/10-common/utils/utils.ts
src/modules/45-projects-orgs/pages/LandingDashboardPageV2/ModuleOverview/Grid/ModuleOverviewGrid.tsx
src/modules/45-projects-orgs/pages/LandingDashboardPageV2/ModuleOverview/Grid/__tests__/ModuleOverviewGrid.test.tsx
src/modules/60-et/RouteDestinations.tsx
src/modules/60-et/components/SideNav/SideNav.tsx
src/modules/60-et/components/SideNav/__test__/__snapshots__/SideNav.test.tsx.snap
src/modules/60-et/pages/ET-agent-control/ET-agents/ETAgents.tsx
src/modules/60-et/pages/ET-agent-control/ETSettings.tsx
src/modules/60-et/pages/ET-agent-control/__tests__/ETSettings.test.tsx
src/modules/60-et/pages/events-summary/ETEventsSummary.module.scss
src/modules/60-et/pages/events-summary/ETEventsSummary.module.scss.d.ts
src/modules/60-et/pages/events-summary/ETEventsSummary.tsx
src/modules/60-et/pages/events-summary/__tests__/ETEventsSummary.test.tsx
src/modules/60-et/pages/events-summary/__tests__/__snapshots__/ETEventsSummary.test.tsx.snap
src/services/cd-ng/index.tsx

Added Events Summary page, Agents Page, and Tokens page to new Continuous Error Tracking module. Pages function the same as existing logic in SRM. Features behind feature flag.
NA
<details>
- [X ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ X] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>
<details>
- …

feat: [CET-1181] Added Error Tracking Functionality To CET Module

---

src/index.html

NA
<details>
</details>
<details>
</details>

feat: [IDP-198]: Adding timestamp for remoteEntry file of IDP

---

src/modules/85-cv/pages/health-source/HealthSourceDrawer/component/customiseHealthSource/CustomiseHealthSource.utils.tsx
src/modules/85-cv/pages/health-source/HealthSourceDrawer/component/customiseHealthSource/__tests__/CustomiseHealthSource.utils.test.ts
src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/CommonHealthSource.constants.ts
src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/CommonHealthSource.utils.ts
src/modules/85-cv/pages/health-source/connectors/CommonHealthSource/__tests__/CommonHealthSource.utils.test.ts

1. Addressing scenario for clicking on Configurations tab for ELK health source
NA
<details>
</details>
<details>
- Fix …

feat: [SRM-14389]: addressing scenario for clicking on Configurations tab for ELK health source

---

package.json
src/modules/10-common/hooks/useNavModuleInfo.ts
src/modules/10-common/navigation/MainNav/ModuleLinks.tsx
src/modules/10-common/strings/strings.en.yaml
src/modules/45-projects-orgs/components/Menu/ContextMenu.tsx
src/modules/45-projects-orgs/components/ModuleListCard/ModuleListCard.tsx
src/modules/45-projects-orgs/components/ModuleRenderer/DefaultRenderer.tsx
src/modules/45-projects-orgs/modals/ModuleSelect/useModuleSelect.tsx
src/modules/45-projects-orgs/pages/projects/views/ProjectListView/ProjectListView.tsx
src/modules/45-projects-orgs/strings/strings.en.yaml
src/modules/45-projects-orgs/utils/utils.ts
src/modules/75-et/strings/strings.en.yaml
src/stringTypes.ts
yarn.lock

dialogs
Adding icons and additional cards to the project creation dialogs
<details>
</details>
<details>
- Fix Prettier: `fix …

feat: [CET-1268]: Add CET module to project

---

cypress/integration/70-pipeline/JenkinsStep.spec.ts
cypress/support/35-connectors/constants.ts
src/modules/10-common/components/ReferenceSelect/ReferenceSelect.tsx
src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
src/modules/40-gitsync/components/GitSyncForm/__tests__/mockdata.ts
src/modules/40-gitsync/components/gitSyncRepoForm/__tests__/__snapshots__/GitSyncRepoForm.test.tsx.snap

NA
<details>
</details>
<details>
</details>

feat: [PL-39029]: Adding All tab in Select Connectors modal

---

src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionTabs/ExecutionTabs.tsx

Replace image in CI with new CET module image
Before:
After:
<details>
</details>
<details> …

feat: [CET-1361]: Update excution tab in CI

---

src/modules/75-cd/components/EnvironmentsV2/EnvironmentDetails/EnvironmentDetailSummary/EnvironmentDetailTable.tsx

NA
<details>
</details>
<details>
</details>
after:

fix: [CDS-71376]: fixed the styles of service name in view table option 

---

src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/ArtifactoryArtifactSource/ArtifactoryArtifactSource.tsx

Before fix -->
After fix --> 
https://github.com/harness/harness-core-ui/assets/96409598/3e142022-afab-423d-bad3-02186e380f1e
<details>
</details>
<details>
- …

fix: [CDS-70188]: Adds support to disable repository field for readonly view of artifactory artifact source template

---

src/modules/70-pipeline/components/PipelineStudio/SaveTemplateButton/SaveAsTemplate.module.scss
src/modules/70-pipeline/components/PipelineStudio/SaveTemplateButton/SaveAsTemplate.module.scss.d.ts
src/modules/70-pipeline/components/PipelineStudio/SaveTemplateButton/useSaveAsTemplate.tsx
src/modules/70-pipeline/components/TemplateLibraryErrorHandling/ReconcileDialog/ReconcileDialog.module.scss
src/modules/70-pipeline/components/TemplateLibraryErrorHandling/ReconcileDialog/ReconcileDialog.module.scss.d.ts
src/modules/70-pipeline/components/TemplateLibraryErrorHandling/ReconcileDialog/ReconcileDialog.tsx
src/modules/70-pipeline/strings/strings.en.yaml
src/modules/70-pipeline/utils/__tests__/useSaveTemplate.test.tsx
src/modules/70-pipeline/utils/useSaveTemplate.ts
src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.module.scss
src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.module.scss.d.ts
src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/SaveTemplatePopover.tsx
src/modules/72-templates-library/components/TemplateStudio/SaveTemplatePopover/__tests__/SaveTemplatePopover.test.tsx
src/stringTypes.ts

- Added OPA on template save
https://github.com/harness/harness-core-ui/assets/106532291/9b95cbea-7edf-442f-bba3-264569862fd1
<details>
</details>
<details>
- …

feat: [CDS-68282] Template Library Integration with OPA - On Save

---

src/modules/70-pipeline/components/RunPipelineModal/RunModalHeader.tsx
src/modules/70-pipeline/components/RunPipelineModal/RunPipelineForm.module.scss
src/modules/70-pipeline/components/RunPipelineModal/RunPipelineForm.module.scss.d.ts
src/modules/70-pipeline/components/RunPipelineModal/RunPipelineForm.tsx
src/modules/70-pipeline/components/RunPipelineModal/__tests__/RunPipelineForm.test.tsx
src/modules/70-pipeline/components/RunPipelineModal/__tests__/__snapshots__/RunPipelineForm.test.tsx.snap

https://github.com/harness/harness-core-ui/assets/98325173/89003903-2432-4c58-be43-6df82cd5e3e6
<details>
</details>
<details>
- …

fix: [CDS-71712]: added error pop-up for stage selection disabled due to error

---

src/modules/20-rbac/pages/ResourceGroupDetails/utils.tsx
src/modules/25-governance/GovernanceApp.tsx
src/modules/25-governance/GovernanceCustomMicroFrontendProps.tsx
src/modules/25-governance/GovernanceCustomMicroFrontendProps.types.ts
src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineActions.ts

Added new hook to return some RBAC Factory data.
Passing some resource group hooks to display and fetch resource group data
NA
<details>
</details>
<details>
- …

feat: [OPA-1326]: harness-core-ui work for new policy pipeline tab

---

src/modules/72-triggers/pages/triggers/TriggerLandingPage/TriggerActivityHistoryPage/TriggerActivityList.tsx
src/modules/72-triggers/pages/triggers/TriggerLandingPage/__tests__/TriggerActivityHistoryPage.test.tsx
src/modules/72-triggers/pages/triggers/TriggerLandingPage/__tests__/TriggerActivityHistoryPageMocks.ts

NA
<details>
</details>
<details>
</details>

fix: [CDS-71613]: Show run sequence id and handled invalid json case for payload

---

src/modules/10-common/layouts/TrialLicenseBanner.tsx
src/modules/10-common/layouts/__tests__/TrialLicenseBanner.test.tsx
src/modules/10-common/layouts/__tests__/__snapshots__/TrialLicenseBanner.test.tsx.snap

NA
<details>
</details>
<details>
</details>

fix: [PLG-964]: removing extend trial button
