- src/modules/85-cv/pages/monitored-service/components/Configurations/Configurations.tsx
- src/modules/85-cv/pages/monitored-service/components/Configurations/__tests__/Configurations.test.tsx
- src/modules/85-cv/utils/CommonUtils.ts
400 error message is not shown in the UI on monitored service save
https://harness.atlassian.net/browse/CVNG-4118
> fix: [CVNG-4118]: Handled error response with status code 400

- cypress/support/70-pipeline/constants.ts
- src/modules/70-pipeline/pages/pipeline-deployment-list/PipelineDeploymentListHeader/ExecutionFilters/ExecutionFilters.tsx
- src/modules/70-pipeline/pages/pipeline-deployment-list/__tests__/filters.json
- src/modules/70-pipeline/utils/PipelineExecutionFilterRequestUtils.ts
- src/modules/70-pipeline/utils/__tests__/PipelineExecutionFilterRequestUtils.test.ts
Bug fix for : https://harness.atlassian.net/browse/CI-3314
Fixed repository name handling in the overall filter payload.
> fix: [CI-3314]: Fix incorrect filter structure sent for Repository name filter

- package.json
- src/modules/10-common/components/GitFilters/__tests__/__snapshots__/GitFilters.test.tsx.snap
- src/modules/35-connectors/components/CreateConnector/CEK8sConnector/__tests__/__snapshots__/CreateCEK8sConnector.test.tsx.snap
- src/modules/35-connectors/components/CreateConnector/HashiCorpVault/__test__/__snapshots__/VaultConnectorFormFields.test.tsx.snap
- src/modules/35-connectors/components/CreateConnector/SumoLogicConnector/__tests__/__snapshots__/CreateSumoLogicConnector.test.tsx.snap
- src/modules/72-triggers/pages/triggers/__tests__/__snapshots__/SchedulePanel.test.tsx.snap
- src/modules/75-ce/components/COEcsSelector/__tests__/__snapshots__/COEcsSelector.test.tsx.snap
- src/modules/75-ce/components/COGatewayConfig/__tests__/__snapshots__/COHealthCheckTable.test.tsx.snap
- src/modules/75-ce/components/COGatewayConfig/__tests__/__snapshots__/CORoutingTable.test.tsx.snap
- src/modules/75-ce/components/CORdsSelector/__tests__/__snapshots__/CORdsSelector.test.tsx.snap
- src/modules/75-ci/components/PipelineSteps/RunStep/__test__/RunStep.test.tsx
- src/modules/75-ci/components/PipelineSteps/RunStep/__test__/RunStepForVMs.test.tsx
- src/modules/75-ci/components/PipelineSteps/RunTestsStep/__test__/RunTestsStep.test.tsx
- src/modules/75-ci/components/PipelineSteps/RunTestsStep/__test__/RunTestsStepForVMs.test.tsx
- yarn.lock
Dropdown values were rendering inside the parent instead of being painted over
https://harness.atlassian.net/browse/PIE-2699
Before:
https://user-images.githubusercontent.com/96711906/155439369-985a80d2-f58c-4272-8854-18f5b8f478b1.mov
After:
https://user-images.githubusercontent.com/96711906/155546683-6690ff37-738a-47c8-bf86-7c4e10706249.mov
> fix: [PIE-2699]: dropdown values not visible

- src/modules/33-auth-settings/pages/AccountOverview/views/AccountDetails.tsx
- src/modules/33-auth-settings/pages/subscriptions/SubscriptionsPage.tsx
- src/services/cd-ng/index.tsx
Updated NG Get Accounts API to require a accountIdentifier query parameter.
[PLG-678](https://harness.atlassian.net/browse/PLG-678)
> fix: [GTM-678]: Added query param to get accounts api

- src/modules/85-cv/pages/monitored-service/components/Configurations/components/Dependency/Dependency.tsx
- src/modules/85-cv/pages/monitored-service/components/Configurations/components/Dependency/__tests__/Dependency.mock.ts
- src/modules/85-cv/pages/monitored-service/components/Configurations/components/Dependency/__tests__/Dependency.test.tsx
- src/modules/85-cv/pages/monitored-service/components/Configurations/components/Service/Service.utils.ts
Support multiple environments for monitored service API.
https://harness.atlassian.net/browse/CVS-9182
> feat: [CVS-9182]: Supported multiple environments for monitored service API

- src/modules/85-cv/components/ErrorTrackingAnalysis/ErrorTrackingAnalysis.constants.ts
- src/modules/85-cv/components/ErrorTrackingAnalysis/ErrorTrackingAnalysis.module.scss
- src/modules/85-cv/components/ErrorTrackingAnalysis/ErrorTrackingAnalysis.module.scss.d.ts
- src/modules/85-cv/components/ErrorTrackingAnalysis/ErrorTrackingAnalysis.tsx
- src/modules/85-cv/components/ErrorTrackingAnalysis/ErrorTrackingAnalysis.types.ts
- src/modules/85-cv/components/ErrorTrackingAnalysis/ErrorTrackingAnalysis.utils.ts
- src/modules/85-cv/components/ErrorTrackingAnalysis/__tests__/ErrorTrackingAnalysis.mocks.ts
- src/modules/85-cv/components/ErrorTrackingAnalysis/__tests__/ErrorTrackingAnalysis.test.tsx
- src/modules/85-cv/components/ErrorTrackingAnalysis/__tests__/ErrorTrackingAnalysis.utils.test.tsx
- src/modules/85-cv/components/ErrorTrackingAnalysis/__tests__/__snapshots__/ErrorTrackingAnalysis.test.tsx.snap
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/ServiceHealth.tsx
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/ErrorTracking.module.scss
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/ErrorTracking.module.scss.d.ts
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/ErrorTracking.tsx
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/__tests__/ErrorTracking.mock.ts
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/__tests__/ErrorTracking.test.tsx
- src/modules/85-cv/strings/strings.en.yaml
- src/services/cv/index.tsx
- src/services/cv/overrides.yaml
- src/stringTypes.ts
Create a separate table for Error Tracking in the SRM Live Monitoring
https://harness.atlassian.net/browse/SRM-9399
> feat: [SRM-9399]: Add Errors to SRM Live Monitoring

- src/modules/35-connectors/components/CreateConnector/ErrorTrackingConnector/CreateErrorTrackingConnector.tsx
- src/modules/35-connectors/components/CreateConnector/ErrorTrackingConnector/utils.ts
- src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts
- src/modules/35-connectors/strings/strings.en.yaml
- src/services/ce/index.tsx
- src/services/ce/swagger.json
- src/services/cv/index.tsx
- src/services/cv/swagger.json
- src/services/portal/index.tsx
- src/services/portal/swagger.json
- src/stringTypes.ts
Removes OverOps SID (service ID) from the connector and uses account ID, Org ID, and Project ID instead
https://harness.atlassian.net/browse/SRM-9295
SID text field removed
> feat: [SRM-9295]: remove SID

- coverage-groups.json
- src/modules/10-common/components/GitContextForm/GitContextForm.tsx
- src/modules/10-common/components/GitContextForm/__tests__/__snapshots__/GitContextForm.test.tsx.snap
- src/modules/35-connectors/components/CreateConnector/commonSteps/ConnectorDetailsStep.module.scss
Changes are : 
- Invalid branch fixes : `GitContextForm` is always initialised with a given <Repo, branch> or <1st Repo, default branch>.Bug was to push branch used for initialising for all the repo.
- CSS fixes : Loading Icon was in far right.And branch Select dropdown size was changing while loading.
- Making Branch list size as 100 as decided for consistency
- Including `GitContextForm` of common under GitSync coverage
https://harness.atlassian.net/browse/PL-22646
**Before fix as in QA now**
https://user-images.githubusercontent.com/63278928/159774873-cb780830-af74-4609-af75-f88547ceecb0.mov
**After fix:** 
https://user-images.githubusercontent.com/63278928/159774393-289e1d7b-ecf8-44a4-b8ea-16d821ac3e6c.mov
- Jest: `retrigger …
> fix: [PL-22646]: Invalid branch fixes

- src/modules/75-ci/components/PipelineSteps/StepCommonFields/StepCommonFieldsInputSet.tsx
If we set limit memory as a runtime input, it doesn’t render on Run Pipeline form unless limit cpu/timeout/run as user is also set as runtime input.
https://harness.atlassian.net/browse/CI-3904
> feat: [CI-3904]: Remove unnecessary conditions during render of fields set as runtime inputs

- src/modules/85-cv/components/ErrorTrackingAnalysis/ErrorTrackingAnalysis.tsx
- src/modules/85-cv/components/ErrorTrackingAnalysis/__tests__/ErrorTrackingAnalysis.test.tsx
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/__tests__/ErrorTracking.test.tsx
Live Monitoring Error Tracking Cluster view issue fixed
https://harness.atlassian.net/browse/SRM-9997
Before:
After:
> fix: [SRM-9997]: Fix Live Monittoring Error Cluster view

- src/modules/35-connectors/components/CreateConnector/ErrorTrackingConnector/CreateErrorTrackingConnector.tsx
- src/modules/35-connectors/components/CreateConnector/ErrorTrackingConnector/utils.ts
- src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts
Adds the url entry for the Error Tracking connector back in for the UI
https://harness.atlassian.net/browse/SRM-9821
> Revert "feat: [SRM-9821]: error tracking remove url input (#8344)"

- cypress/integration/70-pipeline/Environments.spec.ts
- cypress/integration/70-pipeline/Services.spec.ts
> remove unnecessary wait
https://harness.atlassian.net/browse/PIE-3532
> fix: [PIE-3532]: removed unnecessary wait

- package.json
- src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ServerlessAwsLambdaManifest/ServerlessAwsLambdaManifest.tsx
- initialValues was required prop in the component, so it was not desired to keep optional check before accessing any value from that.
- We need to keep types properly. For now, issue is fixed by adding optional chaining. Types will be fixed later and optional chaining will be removed.
https://harness.atlassian.net/browse/CDS-36981
**Before:**
**After:**
> fix: [CDS-36981]: add optional chaining to initialValues in ServerlessAwsLambdaManifest file

- src/modules/35-connectors/components/CreateConnector/ErrorTrackingConnector/CreateErrorTrackingConnector.tsx
- src/modules/35-connectors/components/CreateConnector/ErrorTrackingConnector/utils.ts
- src/modules/35-connectors/pages/connectors/utils/ConnectorUtils.ts
Remove the URL input from the Error Tracking connector since it is already known
https://harness.atlassian.net/browse/SRM-9821
Before
After
> feat: [SRM-9821]: error tracking remove url input

- src/modules/70-pipeline/components/ArtifactsSelection/ArtifactRepository/ArtifactLastSteps/ACRArtifact/ACRArtifact.tsx
- src/modules/75-cd/components/PipelineSteps/AzureInfrastructureStep/AzureInfrastructureStep.tsx
initialisation of subscriptionId field for ACR artifact and Azure infrastructure when subscriptionId exists in the list of subscriptions
https://harness.atlassian.net/browse/CDS-37145
https://user-images.githubusercontent.com/96610348/167442654-39a426cd-cbfc-4509-9d26-9d7d8093152c.mov
https://user-images.githubusercontent.com/96610348/167442692-79918398-db6f-41d8-81eb-95d0bd289cde.mov
> fix: [CDS-37145]: initialisation of subscriptionId field for Azure

- package.json
- src/modules/85-cv/components/ContextMenuActions/ContextMenuActions.module.scss
- src/modules/85-cv/components/ContextMenuActions/ContextMenuActions.module.scss.d.ts
- src/modules/85-cv/components/ContextMenuActions/ContextMenuActions.tsx
- src/modules/85-cv/pages/monitored-service/CVMonitoredService/CVMonitoredService.types.ts
- src/modules/85-cv/pages/monitored-service/CVMonitoredService/components/MonitoredServiceListView/MonitoredServiceListView.tsx
- src/modules/85-cv/strings/strings.en.yaml
- src/stringTypes.ts
Add the ability to copy Error Tracking config from the Monitored Service
https://harness.atlassian.net/browse/SRM-9868
Before:
After:
> feat: [SRM-9868]: Add ET copy config to monitored services

- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/ACRArtifactSource/ACRArtifactSource.tsx
Fix props for refetching subscriptions, registries, repositories for ACR artifact runtime form
(https://harness.atlassian.net/browse/CDS-37258)
https://user-images.githubusercontent.com/96610348/167641536-5fbbfa75-52d2-41f4-8702-c1ed0b448621.mov
> fix: [CDS-37258]: list refetching in ACR artifract runtime form

- package.json
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ArtifactSource/ACRArtifactSource/ACRArtifactSource.tsx
Fix props for refetching subscriptions, registries, repositories for ACR artifact runtime form
(https://harness.atlassian.net/browse/CDS-37258)
https://user-images.githubusercontent.com/96610348/167641290-c0b4823c-0d75-4d7c-b365-2da3aa722943.mov
> fix: [CDS-37258]: list refetching in ACR artifract runtime form hotfix

- src/modules/75-cd/components/PipelineStudio/DeployServiceSpecifications/DeployServiceSpecifications.tsx
If current stage is propagated from a template stage, due to the absence of deployment type in template data, the artifacts and manifests section was not getting rendered. In order to fix this, the template ref is being used to make the get template call and then the deployment type is being obtained from the received yaml.
https://harness.atlassian.net/browse/CDS-37143
https://user-images.githubusercontent.com/96409598/167615997-4a2f5ee7-f440-4cc3-b364-6eb783596202.mov
Loading and error updated behaviour --> 
https://user-images.githubusercontent.com/96409598/167731703-e4ded495-3eef-4ff5-bdb0-55ab2a629187.mov …
> fix: [CDS-37143]: template propagated artifacts and manifests fixed

- src/modules/35-connectors/components/CreateConnector/HashiCorpVault/views/VaultConfigForm.tsx
- src/modules/35-connectors/strings/strings.en.yaml
- src/stringTypes.ts
Added validation for default secret manager checkbox, to be equal to false when read only checkbox is ticked
https://harness.atlassian.net/browse/PL-24810
> fix: [PL-24810]: Disallow ticking default SM for a read only SM in HashiCorp Vault modal

- src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
- src/modules/35-connectors/components/ConnectorReferenceField/__tests__/FormMultiTypeConnectorField.test.tsx
- src/modules/35-connectors/components/ConnectorReferenceField/__tests__/__snapshots__/FormMultiTypeConnectorField.test.tsx.snap
- src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/ManifestStore.tsx
- src/modules/70-pipeline/components/ManifestSelection/__tests__/ManifestStore.test.tsx
- src/modules/70-pipeline/components/ManifestSelection/__tests__/__snapshots__/ManifestStore.test.tsx.snap
Disabling the `continue` button in ManifestWizard till the connector is fetched.
[https://harness.atlassian.net/browse/PIE-3816](https://harness.atlassian.net/browse/PIE-3816)
> fix: [PIE-3816]: continue disabled till connectors are fetched

- src/modules/10-common/RouteDefinitions.ts
- src/modules/85-cv/ErrorTrackingApp.tsx
- src/modules/85-cv/RouteDestinations.tsx
- src/modules/85-cv/components/LogsAnalysis/components/LogAnalysisRow/LogAnalysisRow.utils.ts
- src/modules/85-cv/components/LogsAnalysis/components/LogAnalysisRow/__tests__/LogAnalysisRow.utils.test.ts
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/ErrorTracking.module.scss
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/ErrorTracking.module.scss.d.ts
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/ErrorTracking.tsx
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/__tests__/ErrorTracking.test.tsx
Use Error Tracking microfrontend component the ET Event List
https://harness.atlassian.net/browse/SRM-10723
The full Error List in Monitored Services has been replaced with the ET microfrontend component
> feat: [SRM-10723]: add microfrontend components for Error Tracking

- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ErrorTracking/ErrorTracking.tsx
Fix spacing on the ET Errors tab in SRM
https://harness.atlassian.net/browse/SRM-10723
> fix: [SRM-10723]: Spacing on ET SRM list

- src/modules/70-pipeline/components/PipelineSteps/AdvancedSteps/FailureStrategyPanel/FailureTypeMultiSelect.tsx
- src/modules/70-pipeline/components/PipelineSteps/AdvancedSteps/FailureStrategyPanel/__tests__/__snapshots__/FailureStrategyPanel.test.tsx.snap
- src/modules/70-pipeline/components/PipelineSteps/AdvancedSteps/FailureStrategyPanel/__tests__/__snapshots__/ManualIntervention.test.tsx.snap
- src/modules/70-pipeline/components/PipelineSteps/AdvancedSteps/FailureStrategyPanel/__tests__/__snapshots__/Retry.test.tsx.snap
- src/modules/70-pipeline/strings/strings.en.yaml
- src/stringTypes.ts
Changed the failure strategy step placeholder text
https://harness.atlassian.net/browse/PIE-2157
After:- 
Before:- 
> fix: [PIE-2157]: changed the placeholder text for failure strategy step

- src/modules/70-pipeline/pages/execution/ExecutionErrorTrackingView/ExecutionErrorTrackingView.tsx
The Error Tracking will use different time ranges depending on if the build is running or if it has completed. The time range always uses build start time for the start of the time range. The ending time will be one of 2 cases:
1. current time - When the build is currently running so there are no build end time
2. build end time + 30 mins - When the build is competed (build end time is available)
https://harness.atlassian.net/browse/SRM-10749
Only api calls. screenshots are NA
- …
> feat: [SRM-10749]: Changed ET CI End time to be fixed after build has finish

- src/modules/31-filestore/components/FileStoreList/FileStoreList.module.scss.d.ts
- src/modules/31-filestore/components/MultiTypeFileSelect/FileStoreSelect/FileStoreSelectField.tsx
- src/modules/70-pipeline/components/ManifestSelection/ManifestInterface.ts
- src/modules/70-pipeline/components/ManifestSelection/ManifestListView/ManifestListView.tsx
- src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/CustomRemoteManifest/CustomRemoteManifest.tsx
- src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/HarnessFileStore/HarnessFileStore.tsx
- src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/HarnessFileStore/__tests__/HarnessFileStore.test.tsx
- src/modules/70-pipeline/components/ManifestSelection/ManifestWizardSteps/HarnessFileStore/__tests__/__snapshots__/HarnessFileStore.test.tsx.snap
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/HelmChartManifestSource/HelmChartManifestSource.tsx
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/KustomizeManifestSource/KustomizeManifestSource.tsx
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/KustomizePatchesManifestSource/KustomizePatchesManifestSource.tsx
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/ManifestSourceRuntimeFields/K8sValuesYamlManifestContent.tsx
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/ManifestSourceRuntimeFields/ManifestCommonRuntimeFields.tsx
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/ManifestSourceRuntimeFields/__tests__/ManifestCommonRuntimeFields.test.tsx
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/ManifestSourceRuntimeFields/__tests__/__snapshots__/ManifestCommonRuntimeFields.test.tsx.snap
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/ManifestSourceRuntimeFields/__tests__/mocks.ts
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/OpenshiftParamManifestSource/OpenshiftParamManifestSource.tsx
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/OpenshiftParamManifestSource/__tests__/mocks.ts
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/OpenshiftTemplateManifestSource/OpenshiftTemplateManifestSource.tsx
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/OpenshiftTemplateManifestSource/__tests__/__snapshots__/OpenshiftTemplateManifestSource.test.tsx.snap
- src/modules/75-cd/components/PipelineSteps/K8sServiceSpec/ManifestSource/OpenshiftTemplateManifestSource/__tests__/mocks.ts
NA
<details>
</details>
<details>
</details>
> fix: [CDS-38365]: Openshift template and param support added for custom manifest, and runtimeview implemented for file store

- src/modules/70-pipeline/pages/execution/ExecutionPipelineView/ExecutionGraphView/ExecutionStageDetails/ExecutionStageDetails.tsx
- src/modules/70-pipeline/pages/execution/ExecutionPipelineView/ExecutionGraphView/ExecutionStageDetails/components/ResourceConstraints/ResourceConstraints.tsx
- src/modules/70-pipeline/pages/execution/ExecutionPipelineView/ExecutionGraphView/ExecutionStageDetails/components/ResourceConstraints/__test__/__snapshots__/ResourceConstraints.test.tsx.snap
- src/modules/70-pipeline/strings/strings.en.yaml
- enhance resource constraint step hover message as suggested by docs team
- For serverless deployment type `K8s namespace` word was appearing in Resource Constraints message popover which happened due to new refactoring in diagram, fixed this issue
<details>
</details>
<details>
</details>
> feat: [PIE-4406]: enhance resource constraint step hover message

- src/modules/45-dashboards/components/DashboardCard/DashboardCard.tsx
- src/modules/45-dashboards/components/DashboardResourceModalBody/DashboardResourceModalBody.tsx
- src/modules/45-dashboards/components/DashboardResourceModalBody/__tests__/DashboardResourceModalBody.test.tsx
- src/modules/45-dashboards/constants.ts
- src/modules/45-dashboards/pages/dashboardView/DashboardView.tsx
- src/modules/45-dashboards/pages/dashboardView/__tests__/DashboardView.test.tsx
- src/modules/45-dashboards/pages/folders/FoldersPage.tsx
- src/modules/45-dashboards/pages/folders/form/CreateFolder.tsx
- src/modules/45-dashboards/pages/folders/form/UpdateFolder.tsx
- src/modules/45-dashboards/pages/folders/useDeleteFolder.tsx
- src/modules/45-dashboards/pages/home/CloneDashboardForm.tsx
- src/modules/45-dashboards/pages/home/CreateDashboardForm.tsx
- src/modules/45-dashboards/pages/home/DashboardForm.tsx
- src/modules/45-dashboards/pages/home/HomePage.tsx
- src/modules/45-dashboards/pages/home/UpdateDashboardForm.tsx
- src/modules/45-dashboards/pages/home/__tests__/CloneDashboardForm.test.tsx
- src/modules/45-dashboards/pages/home/__tests__/DashboardForm.test.tsx
- src/modules/45-dashboards/pages/home/__tests__/Dashboards.test.tsx
- src/modules/45-dashboards/strings/strings.en.yaml
- src/services/custom-dashboards/index.tsx
- src/stringTypes.ts
CDB-227 will enforce the Dashboard View and Edit roles within the app.
The main changes happening to the UI as part of this change are
* Support displaying meaningful error messages
* Enforce roles per folder
* Include OOTB folder when assigning a resource group
> feat: [CDB-227]: enforce dashboards view and edit roles

- src/modules/45-dashboards/pages/dashboardView/DashboardView.tsx
- src/modules/45-dashboards/pages/dashboardView/__tests__/DashboardView.test.tsx
- A fix has been applied to prevent a potential TypeError occurring when a Dashboard signedUrl isn't returned from the Dashboard Service.
N/A
<details>
</details>
<details>
</details>
> fix: [CDB-97]: Fixed potential error when DashboardView url fails to return

- src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectMonitoredServiceType/SelectMonitoredServiceType.utils.ts
- src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectMonitoredServiceType/__tests__/SelectMonitoredServiceType.mock.ts
- src/modules/85-cv/components/PipelineSteps/ContinousVerification/components/ContinousVerificationWidget/components/ContinousVerificationWidgetSections/components/SelectMonitoredServiceType/__tests__/SelectMonitoredServiceType.test.tsx
1. Fixing the scenario where templatised monitored service is created with all fixed inputs
NA
<details>
</details>
<details>
</details>
> feat: [SRM-11096]: fixing the scenario where templatised monitored service is created with all fixed inputs

- cypress/integration/75-ce/CreatePerspective.spec.ts
- src/modules/75-ce/components/CloudCostInsightChart/Chart.tsx
- src/modules/75-ce/components/CloudCostInsightChart/ChartLegend.module.scss
- src/modules/75-ce/components/CloudCostInsightChart/ChartLegend.module.scss.d.ts
- src/modules/75-ce/components/CloudCostInsightChart/ChartLegend.tsx
- src/modules/75-ce/components/PerspectiveBuilder/PerspectiveBuilder.tsx
- src/modules/75-ce/components/PerspectiveBuilderPreview/PerspectiveBuilderPreview.tsx
- src/modules/75-ce/components/PerspectiveExplorerGroupBy/PersepectiveExplorerGroupBy.module.scss
- src/modules/75-ce/components/PerspectiveExplorerGroupBy/PerspectiveExplorerGroupBy.tsx
- src/modules/75-ce/components/PerspectivePreferences/PerspectivePreferences.module.scss
- src/modules/75-ce/components/PerspectivePreferences/PerspectivePreferences.module.scss.d.ts
- src/modules/75-ce/components/PerspectivePreferences/PerspectivePreferences.tsx
- src/modules/75-ce/components/PerspectivePreferences/__test__/PerspectivePreferences.test.tsx
- src/modules/75-ce/components/PerspectiveReportsAndBudget/PerspectiveReportsAndBudgets.tsx
- src/modules/75-ce/components/PerspectiveReportsAndBudget/__test__/PerspectiveReportsAndBudget.test.tsx
- src/modules/75-ce/components/PerspectiveReportsAndBudget/__test__/__snapshots__/PerspectiveReportsAndBudget.test.tsx.snap
- src/modules/75-ce/pages/perspective-builder/CreatePerspectivePage.tsx
- src/modules/75-ce/pages/perspective-details/PerspectiveDetailsPage.module.scss
- src/modules/75-ce/pages/perspective-details/PerspectiveDetailsPage.tsx
- src/modules/75-ce/pages/perspective-details/__test__/__snapshots__/PerspectiveDetailsPage.test.tsx.snap
- src/modules/75-ce/strings/strings.en.yaml
- src/modules/75-ce/utils/perspectiveUtils.ts
- src/queries/ce/fetch_perspective_time_series.gql
- src/services/ce/services.ts
- src/stringTypes.ts
Allow users to set perspective preferences in create perspective flow and perspective time series chart.
https://harness.atlassian.net/browse/CCM-7436
> feat: [CCM-7436]: Perspective Preferences

- src/modules/70-pipeline/components/execution/StepDetails/views/HarnessApprovalView/HarnessApprovalView.tsx
Added Manual Intervention tab under approval stage with failure strategy.
https://user-images.githubusercontent.com/73639897/179738854-c4dc4c6b-6a24-4fd1-9028-b48b4e822162.mov
<details>
</details>
<details>
</details>
> fix: [PIE-1787]: Added MI tab under approval stage with failure strategy

- src/modules/70-pipeline/components/PipelineStudio/ExecutionGraph/ExecutionGraph.tsx
- src/modules/70-pipeline/components/PipelineStudio/ExecutionGraph/ExecutionGraphUtil.ts
- src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineActions.ts
- src/modules/70-pipeline/components/PipelineStudio/RightDrawer/RightDrawer.tsx
- src/modules/70-pipeline/components/PipelineStudio/hooks/useSaveTemplateListener.ts
- propagated `isRollback` to conditionally check `rollbackSteps/steps` while updation/addition of steps.
https://user-images.githubusercontent.com/100121280/180965016-2351d377-1dfb-4728-8e49-25aa8e23e983.mov
<details>
</details>
<details>
</details>
> fix: [CDS-39753]: updation/edit of steps/rollbackSteps based on rollack state

- src/modules/70-pipeline/components/InputSetForm/InputSetForm.tsx
Show error response from API if input set doesn't exist.
<details>
</details>
<details>
</details>
> fix: [PL-26686]: Show input set error response

- src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineActions.ts
- src/modules/70-pipeline/components/PipelineStudio/PipelineContext/PipelineContext.tsx
- src/modules/70-pipeline/components/PipelineStudio/RightDrawer/RightDrawer.tsx
- src/modules/70-pipeline/hooks/useAddStepTemplate.ts
- src/modules/70-pipeline/strings/strings.en.yaml
- src/modules/70-pipeline/utils/stageHelpers.ts
- src/modules/70-pipeline/utils/templateUtils.ts
- src/modules/72-templates-library/components/TemplateSelector/TemplateSelectorLeftView/TemplateSelectorLeftView.module.scss
- src/modules/72-templates-library/components/TemplateSelector/TemplateSelectorLeftView/TemplateSelectorLeftView.module.scss.d.ts
- src/modules/72-templates-library/components/TemplateSelector/TemplateSelectorLeftView/TemplateSelectorLeftView.tsx
- src/modules/72-templates-library/components/TemplateSelector/TemplateSelectorLeftView/__tests__/__snapshots__/TemplateSelectorLeftView.test.tsx.snap
- src/modules/75-cd/components/PipelineStudio/DeployStageSpecifications/__tests__/DeployStageSpecifications.test.tsx
- src/modules/75-cd/components/TemplateStudio/DeploymentTemplateCanvas/DeploymentTemplateForm/components/ExecutionPanel/ExecutionPanel.tsx
- src/modules/75-cf/pages/pipeline-studio/views/StageOverview/__tests__/FeatureStageSpecifications.test.tsx
- src/modules/75-cf/pages/pipeline-studio/views/StageOverview/__tests__/StageOverviewTestHelper.ts
- src/stringTypes.ts
Adds support to show linked templates in template selector for deployment template and for resolution of deployment template to store stepTemplateRefs in context
NA
https://user-images.githubusercontent.com/96409598/192143291-2a212fa5-a7ac-4fd7-afc5-d1edb3d06580.mov
<details>
</details>
<details>
</details>
> fix: [CDS-42730]: Filtering support added for linked templates

- src/modules/35-connectors/pages/connectors/ConnectorsPage.tsx
- src/modules/35-connectors/pages/connectors/__tests__/ConnectorsPage.test.tsx
Refactored code to fix list api being called 3 time to 1 time
Test:
1. Initial Render with no filters.
2. Initial Render with Git filters.
3. Initial Render with common filters
4. Page change 
5. Search with and w/o page change.
NA
<details>
</details>
<details>
- Fix Prettier: `fix …
> feat: [PL-20359]: Fixed multiple list call issue on connectors page

- src/modules/75-cf/pages/onboarding/OnboardingDetailPage.tsx
- src/modules/75-cf/pages/onboarding/__test__/SetUpYourApplicationView.test.tsx
- src/modules/75-cf/pages/onboarding/__test__/SetUpYourCodeView.test.tsx
- src/modules/75-cf/pages/onboarding/views/SetUpYourApplicationView.tsx
- src/modules/75-cf/pages/onboarding/views/SetUpYourCodeView.tsx
- src/modules/75-cf/pages/onboarding/views/ValidatingYourFlagView.module.scss
Step was added for Set Up Your Code (readme), undo this and put content back under SDK Key creation in step 2
JIRA: https://harness.atlassian.net/browse/FFM-5391
- put content back in SetUpYourApplicationView
- remove step from stepper at top of page
- update unit tests
<details>
</details>
<details>
- Cypress Rest: …
> feat: [FFM-5391]: remove additional step added to FF Onboarding flow

- src/modules/75-cd/pages/get-started-with-cd/CreateKubernetesDelegateWizard/CreateK8sDelegate.tsx
- src/modules/75-cd/pages/get-started-with-cd/__tests__/DelegateOnboarding.test.tsx
- src/modules/75-cd/pages/get-started-with-cd/__tests__/GetStartedWithCD.test.tsx
delegate name with capitals is failing, so in order to get this corrected we are restricting the random id with numbers and  small case alphabet
collision probability 
[screen-capture (7).webm](https://user-images.githubusercontent.com/73115842/203759183-b1fe8582-ad5a-4e51-ac59-58635149f344.webm)
NA
<details>
</details>
<details>
- Rebase: …
> fix: [DEL-5259]: custom string nano id

- src/modules/70-pipeline/components/PipelineInputSetForm/CICodebaseInputSetForm.tsx
- src/modules/70-pipeline/utils/CIUtils.ts
- src/modules/70-pipeline/utils/__tests__/CIUtils.test.ts
This fixes: https://harness.atlassian.net/browse/CI-6814
This PR handles logic for onprem git connectors which have a slightly different git repo url as compared to SaaS git connectors.
NA
<details>
</details>
<details>
- Cypress CD: `retrigger …
> fix: [CI-6814]: Fix logic to fetch repo name for onprem connectors

- src/modules/70-pipeline/components/InputSetForm/InputSetForm.tsx
- src/modules/70-pipeline/components/PipelineVariablesContext/PipelineVariablesContext.tsx
- src/modules/70-pipeline/components/RunPipelineModal/RunPipelineForm.tsx
- Remove the duplicate variables call in the run pipeline form . Made the call `lazy` dependent on the `pipeline` object being
empty.
- Remove the duplicate resolved pipeline call in the input set form
https://user-images.githubusercontent.com/106532291/224626650-5eae846c-46fa-4059-8418-8262154ef798.mov
<details>
</details>
<details>
- Coverage: …
> chore: [PIE-8685]: fixing two variables call in the run pipeline form

- src/modules/85-cv/pages/changes/CVChanges.tsx
- src/modules/85-cv/pages/changes/__tests__/CVChangesFilterReset.test.tsx
- src/modules/85-cv/pages/changes/__tests__/data-mocks/ChangeEventListMock.ts
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesAndServiceDependency/components/ChangesTable/ChangesTable.tsx
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesAndServiceDependency/components/ChangesTable/ChangesTable.types.ts
- src/modules/85-cv/pages/monitored-service/components/ServiceHealth/components/ChangesAndServiceDependency/components/ChangesTable/__tests__/ChangesTable.test.tsx
Changes:
1. Reset all filters if the user changes the project
2. Reset page number if the user changes the project or apply any filter(s)
NA
<details>
</details>
<details>
- Cypress Pipeline: `retrigger …
> fix: [SRM-14384]: Update to reset filters when user changes the project

- src/modules/75-cf/hooks/__tests__/useEnvironmentSelectV2.test.tsx
- src/modules/75-cf/hooks/useEnvironmentSelectV2.tsx
- src/modules/75-cf/pages/feature-flags/FeatureFlagsPage.tsx
- src/modules/75-cf/pages/feature-flags/components/AllEnvironmentsFlagsListing.tsx
- src/modules/75-cf/pages/feature-flags/components/__tests__/AllEnvironmentsFlagsListing.test.tsx
- src/services/cf/index.tsx
This PR replaces usage of the `useGetAllEnvironmentFlags` hook with the `useGetProjectFlags` hook.
> chore: [FFM-7568]: Change `useGetAllEnvironmentFlags` to `useGetProjectFlags`

- src/modules/70-pipeline/pages/execution/ExecutionLandingPage/ExecutionTabs/ExecutionTabs.tsx
- src/modules/75-ci/components/PipelineSteps/RunTestsStep/RunTestsStepBase.tsx
- src/modules/75-ci/components/PipelineSteps/RunTestsStep/__test__/RunTestsStep.test.tsx
- src/modules/75-ci/components/PipelineSteps/RunTestsStep/__test__/__snapshots__/RunTestsStep.test.tsx.snap
Since the release of CET and the support of licensing. We are now requiring an active license to use CET in CI pipeline executions.
NA
<details>
</details>
<details> …
> feat: [CET-1330]: Require license to use ET in CI

- cypress/integration/70-pipeline/JenkinsStep.spec.ts
- cypress/support/35-connectors/constants.ts
- src/modules/10-common/components/ReferenceSelect/ReferenceSelect.tsx
- src/modules/35-connectors/components/ConnectorReferenceField/ConnectorReferenceField.tsx
- src/modules/35-connectors/components/ConnectorReferenceField/FormMultiTypeConnectorField.tsx
- src/modules/40-gitsync/components/GitSyncForm/__tests__/mockdata.ts
- src/modules/40-gitsync/components/gitSyncRepoForm/__tests__/__snapshots__/GitSyncRepoForm.test.tsx.snap
NA
<details>
</details>
<details>
</details>
> feat: [PL-39029]: Added `All` tab in select or create connector modal

- src/modules/10-common/strings/strings.en.yaml
- src/modules/75-cet/RouteDestinations.tsx
- src/services/audit/index.tsx
- src/stringTypes.ts
Added two new resources using AuditTrailFactory.registerResouceHandler() to enable viewing of CET audit trail entries for related to CET agent tokens and CET critical event definitions
NA
<details>
</details>
<details>
- Cypress CD: `retrigger …
> feat: [CET-1364] Add audit trail entries for CET resource events
